.gitignore, deploy-exclude.lst, deploy.php, simple-shop-connector.php
Deploy script pro build nových balíčků
Deploy script se volá:
```shell
php deploy.php v1.2.3
```
kde `v1.2.3` je číslo verze, pro kterou se balíček sestavuje.
Script po spuštění:
- vytvoří složku `dist/`, pokud neexistuje,
- vyprázdní složku `dist/`, pokud existuje,
- v souboru `simple-shop-connector.php` napíše do hlaviček verzi,
- vytvoři `.zip` s projektem a s názvem `simple-shop-connector-v1.2.3.zip`, kde `v1.2.3` je zadaná verze a uloží jej do složky `dist/`.
=> Deploy script

includes/class.ssc_cron.php
The notification emails about post becoming available were sent to all users of the site. This should be the fix.
Added TODO to optimize the code
=> Fix notification emails

src/Cron.php
Fix email notification driped content
=> Fix the email notifications

composer.json, composer.lock, src/Plugin.php
Remove the required plugins installer, fixes #11
=> Remove tgmpa

src/Admin.php
Fix ajax response
```
Content-Type: text/html; charset=UTF-8
```
```
Content-Type: application/json; charset=UTF-8
```
=> Fix ajax response

composer.json, composer.lock, src/Plugin.php
Nově se klient bude připojovat na SS API místo VF API. Je to důležité s ohledem na připravované změny ze strany API a projektů VF+SS.
=> Use SimpleShop.cz API instead of Vyfakturuj API

css/ssc.css, deploy.php, languages/simpleshop-cz-cs_CZ.po, simpleshop-cz.php, src/Access.php, src/Admin.php, src/Cron.php, src/Group.php, src/Gutenberg.php, src/Helpers.php, src/Loader.php, src/Membership.php, src/Metaboxes.php, src/Plugin.php, src/Rest.php, src/Settings.php, src/Shortcodes.php, src/SimpleShop.php, src/Vyfakturuj/VyfakturujAPI.php
Oprava Code style. Provedeno automaticky, s tím že některé vyloženě ošklivé části kódu jsem upravil ručně.
Bez změny sémantiky.
=> Fix Code Style

.gitignore, js/gutenberg/ss-gutenberg-test.js, package-lock.json, package.json, src/Gutenberg.php, webpack.config.js
Ahoj,
posílám první verzi s build procesem s ukázkovým blokem. Podívej se na to, prosím. Pokoušel jsem se nevymýšlet nic speciálního, jenom využívám standardních knihoven, které WordPress poskytuje. V pull requestu okomentuju kód.
Na začátku prosím nezapomeň dát `npm install`
Dan
=> Build process

composer.json, composer.lock, src/Plugin.php
Odstranění nepoužívaného balíčku TGMPA
=> Remove unused TGMPA package

composer.json, composer.lock, src/Shortcodes.php
Úprava SS kódu generovaného backendem WP na nový formát.
=> New SS Form code

deploy-exclude.lst
Add new excludes (NPM files) for package building tool
=> Deploy script: Add build excludes

readme.txt, simpleshop-cz.php
=> Wordpress -> WordPress

readme.txt
Otestováno podporou Simpleshop
=> Readme: Declare compatibility with WordPress 5.6

src/Admin.php
=> Admin: Fix label i18n

readme.txt
Otestována kompatibilita s WP 5.7
=> Readme: Mark tested with WP 5.7

src/Admin.php
Vyfiltruje aktivní produkty (archivované produkty jsou odstraněny) a seřadí je podle jména.
=> Products: List only active products, sort products by name

src/Rest.php
Úprava textace v e-mailu pro uživatele, kteří již mají účet. 
Heslo: [Změnit ho můžete zde](https://example.com)
Heslo: _Vaše stávající heslo (které jste si nastavil/a nebo jsme Vám jej poslali v předchozím e-mailu). Pokud si heslo nepamatujete, [můžete si jej resetovat](https://example.com)._
=> Rest: Better text for users which already have a account

src/Settings.php
Oprava drobné chyby bez vlivu na chování aplikace
=> Settings: Remove duplicated code

readme.txt
Jen překlad Readme do angličtiny, aby byl snazší překlad do Slovenštiny a dalších jazyků.
=> Readme: Switch readme to anglish language

src/Admin.php, src/Metaboxes.php
Opravy CR pro PR #96:
- oprava formátování na jednotný tvar podle [WordPress Coding Standards](https://developer.wordpress.org/coding-standards/wordpress-coding-standards/)
- oprava XSS v souboru `src/Metaboxes.php`, které vznikly v rámci úprav #96
- oprava HTML v souboru `src/Metaboxes.php`, které vznikly v rámci úprav #96
- sjednocení PHP (`<?php echo ` místo `<?=`)
=> CR fixes for #96

src/Rest.php
=> Change email date

js/gutenberg/ss-gutenberg.js, readme.txt, simpleshop-cz.php, src/Metaboxes.php, src/Settings.php
Úprava a oprava textů v EN, příprava na kompletaci překladů
=> Text & strings: Update & fix the EN strings

LICENSE, deploy.php, simpleshop-cz.php, src/Access.php, src/Admin.php, src/Cron.php, src/Group.php, src/Gutenberg.php, src/Helpers.php, src/Loader.php, src/Membership.php, src/Metaboxes.php, src/Plugin.php, src/Rest.php, src/Settings.php, src/Shortcodes.php, src/SimpleShop.php, src/Vyfakturuj/VyfakturujAPI.php
Sjenocení licentních a (c)opyright deklarací
=> License: Update to 2022

readme.txt
Oprava názvu pluginu, který měl být ve verzi 2.6.0 přejmenován, ale změny se nepropsaly do všech míst.
=> Readme: Update plugin propagation (fix)
